
/* var idade = prompt("Digite a sua idade");


if (idade  != null && idade != undefined) {
document.write("a sua idade é "+ idade);
}
else {
    document.write("a sua idade não pode ser nula, digite um valor");

}
*/
/* var lista  = ['rosa' , 'cravo' , 'tulipa', 'margarida']

console.log(lista[2]);


var d = new Date();
console.log(d.getDate());
console.log(d.getDay());
console.log(d.getHours());
console.log(d.getMinutes());
*/


var lista = ['Alemanha','Inglaterra','Escócia'];
console.log(lista);

lista.push('Polônia');
console.log(lista);

lista.pop('Inglaterra');
console.log(lista);