

var list = ["maça", "uva", "pera", "laranja"];
var frutas = [{nome: "maça", cor: "vermelha", sabor: "doce ou ácido."}, {nome:"uva", cor:"roxa", sabor: "doce ou ácido"}];

//list.push("maça");
//list.pop();
//console.log(list.length)
//console.log(list.reverse());
document.writeln("A  Lista "+ list.join(' - ') + " tem " + (list.length) +  " de tamanho");
document.write("<br>Agora é " + list.reverse().join(' - ') + "<br>" );

document.write("<br>");


console.log(list);
console.log(list.toString());
console.log(list.join(" - "));

console.log(frutas);

/*console.log(list[0]);
console.log(list.toString()[4]);*/